"""
src/explain/counterfactual.py

Phase-3 counterfactual explainer: CAL-guided, lightweight STONED-SELFIES
"Approach B" exactly as decided in interface_planning.md / integration_final.md.
Only runs when main.py is invoked with --phase3, because -- as discussed --
this is the expensive part of the pipeline; everything here is written to
minimise how much of that cost is unavoidable:

  1. att_o for the query molecule is computed ONCE (predict_with_attention).
  2. Candidate SMILES are generated by random SELFIES token mutation -- pure
     RDKit/selfies, CPU-only, no model calls.
  3. Candidates are filtered by Maximum-Common-Substructure overlap with the
     query's causal atoms -- again pure RDKit, CPU-only, no model calls, and
     done BEFORE any 3D embedding, so the ~60% of candidates that get
     filtered out never pay the ETKDG/MMFF94 cost either.
  4. Only the surviving candidates are 3D-embedded and scored, and they are
     scored through predict_smiles() in batches (not one model call per
     candidate) -- this is the single biggest lever on wall-clock cost,
     since PhysNet/ChemNet are already batch-vectorized.
  5. DBSCAN + rcf_explain-style selection picks a small, structurally
     diverse set of "up" and "down" counterfactuals from the survivors.

Nothing here calls the model per-candidate in a Python loop; the only model
calls are one predict_with_attention() (query) and one batched predict_smiles() (survivors).
"""

import random
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

import numpy as np
import selfies as sf
import torch
from rdkit import Chem, DataStructs
from rdkit.Chem import AllChem, rdFMCS
from sklearn.cluster import DBSCAN

from configs.config import Config
from src.inference.predict import predict_smiles, predict_with_attention
from src.models.physchem_cal import PhysChemCAL


@dataclass
class Counterfactual:
    """One accepted counterfactual candidate, ready to hand to results_logger.log_counterfactuals()."""
    smiles: str
    pred: float
    similarity: float
    direction: str          # "up" or "down"
    changed_atom_count: int
    causal_overlap: float   # fraction of changed query atoms that were causal (0-1)


def _mutate_selfies_tokens(tokens: List[str], alphabet: List[str], rng: random.Random) -> List[str]:
    """Apply exactly one random STONED-style mutation (replace / insert / delete) to a SELFIES token list; returns a new list, does not mutate `tokens` in place."""
    tokens = list(tokens)
    if len(tokens) == 0:
        return [rng.choice(alphabet)]

    op = rng.choice(["replace", "insert", "delete"] if len(tokens) > 1 else ["replace", "insert"])
    pos = rng.randrange(len(tokens))
    if op == "replace":
        tokens[pos] = rng.choice(alphabet)
    elif op == "insert":
        tokens.insert(pos, rng.choice(alphabet))
    else:  # delete
        tokens.pop(pos)
    return tokens


def generate_stoned_candidates(query_smiles: str, n_mutations: int, seed: int = 42) -> List[str]:
    """Generate up to `n_mutations` structurally-valid, unique candidate SMILES by single-token SELFIES mutations of the query molecule.

    Every SELFIES token sequence decodes to a chemically valid molecule by
    construction, so the only extra validation needed is an RDKit sanitize
    pass (guards against pathological cases the SELFIES grammar still allows
    but RDKit rejects, e.g. extreme valence configurations) and
    deduplication against the query and previously accepted candidates.
    """
    rng = random.Random(seed)
    try:
        query_selfies = sf.encoder(query_smiles)
    except Exception:
        return []
    base_tokens = list(sf.split_selfies(query_selfies))
    alphabet = list(sf.get_semantic_robust_alphabet())

    query_canonical = Chem.MolToSmiles(Chem.MolFromSmiles(query_smiles))
    seen: Set[str] = {query_canonical}
    candidates: List[str] = []

    attempts = 0
    max_attempts = n_mutations * 4  # allow some slack for invalid/duplicate mutations
    while len(candidates) < n_mutations and attempts < max_attempts:
        attempts += 1
        mutated_tokens = _mutate_selfies_tokens(base_tokens, alphabet, rng)
        try:
            candidate_smiles = sf.decoder("".join(mutated_tokens))
        except Exception:
            continue
        mol = Chem.MolFromSmiles(candidate_smiles)
        if mol is None:
            continue
        canonical = Chem.MolToSmiles(mol)
        if canonical in seen:
            continue
        seen.add(canonical)
        candidates.append(canonical)

    return candidates


def _mcs_changed_query_atoms(query_mol: "Chem.Mol", candidate_mol: "Chem.Mol") -> Optional[Set[int]]:
    """Find which query-atom indices are NOT part of the Maximum Common Substructure shared with `candidate_mol`.

    Returns None if no MCS match could be computed at all (extremely
    dissimilar molecules) -- callers should treat that as "filter out".
    """
    result = rdFMCS.FindMCS([query_mol, candidate_mol], timeout=5, ringMatchesRingOnly=True)
    if result.canceled or result.numAtoms == 0:
        return None
    mcs_mol = Chem.MolFromSmarts(result.smartsString)
    if mcs_mol is None:
        return None
    match = query_mol.GetSubstructMatch(mcs_mol)
    if not match:
        return None
    all_atoms = set(range(query_mol.GetNumAtoms()))
    return all_atoms - set(match)


def filter_by_causal_overlap(query_smiles: str, candidates: List[str], causal_atoms: Set[int],
                              min_overlap: int) -> List[Tuple[str, Set[int]]]:
    """Keep only candidates whose MCS-changed query atoms include at least `min_overlap` causal atoms (Stage 10b of integration_final.md, "Approach B" core).

    Returns list of (candidate_smiles, changed_atoms) for survivors --
    changed_atoms is kept around so the caller can later compute the
    CAL-ExMol causal-alignment score without recomputing MCS.
    """
    query_mol = Chem.MolFromSmiles(query_smiles)
    survivors = []
    for cand in candidates:
        cand_mol = Chem.MolFromSmiles(cand)
        if cand_mol is None:
            continue
        changed = _mcs_changed_query_atoms(query_mol, cand_mol)
        if changed is None:
            continue
        if len(changed & causal_atoms) >= min_overlap:
            survivors.append((cand, changed))
    return survivors


def _tanimoto_similarity(query_mol: "Chem.Mol", other_mol: "Chem.Mol") -> float:
    """ECFP4 (Morgan radius=2) Tanimoto similarity between two molecules."""
    fp_a = AllChem.GetMorganFingerprintAsBitVect(query_mol, radius=2, nBits=2048)
    fp_b = AllChem.GetMorganFingerprintAsBitVect(other_mol, radius=2, nBits=2048)
    return DataStructs.TanimotoSimilarity(fp_a, fp_b)


def _select_diverse(direction_candidates: List[Dict], eps: float, top_k: int) -> List[Dict]:
    """DBSCAN-cluster candidates by structural similarity, then pick the highest-similarity representative from each of the top `top_k` clusters (Stage 12 of integration_final.md) -- keeps the final counterfactual set structurally diverse rather than many near-duplicates."""
    if len(direction_candidates) == 0:
        return []
    if len(direction_candidates) == 1:
        return direction_candidates

    fps = [c["_fp"] for c in direction_candidates]
    n = len(fps)
    dist = np.zeros((n, n), dtype=np.float32)
    for i in range(n):
        for j in range(i + 1, n):
            sim = DataStructs.TanimotoSimilarity(fps[i], fps[j])
            dist[i, j] = dist[j, i] = 1.0 - sim

    labels = DBSCAN(eps=eps, min_samples=1, metric="precomputed").fit_predict(dist)

    best_per_cluster: Dict[int, Dict] = {}
    for cand, label in zip(direction_candidates, labels):
        current = best_per_cluster.get(label)
        if current is None or cand["similarity"] > current["similarity"]:
            best_per_cluster[label] = cand

    ranked = sorted(best_per_cluster.values(), key=lambda c: c["similarity"], reverse=True)
    return ranked[:top_k]


def generate_counterfactuals(model: PhysChemCAL, query_smiles: str, label_mean: float, label_std: float,
                              device: torch.device, config: Config) -> Dict[str, object]:
    """Full Phase-3 pipeline for one query molecule: causal atoms -> mutate -> MCS-filter -> batched score -> cluster/select -> alignment score.

    Args:
        model: trained PhysChemCAL (eval mode is enforced internally).
        query_smiles: the molecule to explain.
        label_mean, label_std: label normalisation stats from the checkpoint.
        device: torch device.
        config: Config, for CF_* hyperparameters.
    Returns:
        dict with keys: query_smiles, query_pred, causal_atom_count,
        counterfactuals (list[Counterfactual]), alignment_score (float or None).
    """
    query_pred, att_o = predict_with_attention(model, query_smiles, label_mean, label_std, device)
    if att_o is None:
        return {
            "query_smiles": query_smiles, "query_pred": float("nan"),
            "causal_atom_count": 0, "counterfactuals": [], "alignment_score": None,
        }

    causal_atoms = {i for i, w in enumerate(att_o) if w > config.CF_CAUSAL_THRESHOLD}

    raw_candidates = generate_stoned_candidates(query_smiles, config.CF_N_MUTATIONS, seed=config.SEED)
    survivors = filter_by_causal_overlap(query_smiles, raw_candidates, causal_atoms, config.CF_MCS_MIN_OVERLAP)

    if len(survivors) == 0:
        return {
            "query_smiles": query_smiles, "query_pred": query_pred,
            "causal_atom_count": len(causal_atoms), "counterfactuals": [], "alignment_score": None,
        }

    survivor_smiles = [s for s, _ in survivors]
    survivor_changed = {s: changed for s, changed in survivors}

    # The one batched model call over all survivors -- see module docstring.
    preds = predict_smiles(model, survivor_smiles, label_mean, label_std, device,
                            batch_size=config.CF_PREDICT_BATCH_SIZE)

    query_mol = Chem.MolFromSmiles(query_smiles)
    up_pool, down_pool = [], []
    for smi, pred in zip(survivor_smiles, preds):
        if pred != pred:  # NaN check (shouldn't happen for MCS-validated candidates, but guard anyway)
            continue
        cand_mol = Chem.MolFromSmiles(smi)
        similarity = _tanimoto_similarity(query_mol, cand_mol)
        changed = survivor_changed[smi]
        overlap = len(changed & causal_atoms) / len(changed) if len(changed) > 0 else 1.0
        fp = AllChem.GetMorganFingerprintAsBitVect(cand_mol, radius=2, nBits=2048)
        entry = {
            "smiles": smi, "pred": pred, "similarity": similarity,
            "changed_atom_count": len(changed), "causal_overlap": overlap, "_fp": fp,
        }
        if pred > query_pred + config.CF_DELTA:
            up_pool.append(entry)
        elif pred < query_pred - config.CF_DELTA:
            down_pool.append(entry)

    up_selected = _select_diverse(up_pool, config.CF_DBSCAN_EPS, config.CF_TOP_K_EACH_DIRECTION)
    down_selected = _select_diverse(down_pool, config.CF_DBSCAN_EPS, config.CF_TOP_K_EACH_DIRECTION)

    counterfactuals: List[Counterfactual] = []
    for entry in up_selected:
        counterfactuals.append(Counterfactual(
            smiles=entry["smiles"], pred=entry["pred"], similarity=entry["similarity"],
            direction="up", changed_atom_count=entry["changed_atom_count"], causal_overlap=entry["causal_overlap"],
        ))
    for entry in down_selected:
        counterfactuals.append(Counterfactual(
            smiles=entry["smiles"], pred=entry["pred"], similarity=entry["similarity"],
            direction="down", changed_atom_count=entry["changed_atom_count"], causal_overlap=entry["causal_overlap"],
        ))

    alignment_score = (
        sum(cf.causal_overlap for cf in counterfactuals) / len(counterfactuals)
        if counterfactuals else None
    )

    return {
        "query_smiles": query_smiles,
        "query_pred": query_pred,
        "causal_atom_count": len(causal_atoms),
        "counterfactuals": counterfactuals,
        "alignment_score": alignment_score,
    }
